import type { Metadata } from "next";
import "../globals.css";
import FontAwesomeConfig from "./font-awesome-config";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faPhoneAlt, faMapMarkerAlt, faEnvelope, faCommentAlt } from '@fortawesome/free-solid-svg-icons';
import { faFacebookF, faTwitter, faInstagram, faYoutube, faLinkedinIn } from '@fortawesome/free-brands-svg-icons';


import '@fortawesome/fontawesome-svg-core/styles.css';
// import { config } from '@fortawesome/fontawesome-svg-core';
// config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically since it's being imported.


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FontAwesomeConfig />
        {/* Top Bar */}
        <div className="bg-blue-900 text-white py-2 px-6 flex justify-between items-center ">
          <div className="flex items-center space-x-6">
            <div className="flex items-center text-sm">
              <FontAwesomeIcon icon={faPhoneAlt} className="mr-2 small text-sm " />
              <span className="text-sm">+234 803 123 4567</span>
            </div>
            <div className="flex items-center">
              <FontAwesomeIcon icon={faMapMarkerAlt} className="mr-2 text-xs" />
              <span className="text-sm">Victoria Island, Lagos, Nigeria</span>
            </div>
            <div className="flex items-center">
              <FontAwesomeIcon icon={faEnvelope} className="mr-2 text-xs" />
              <span className="text-sm">info@myhome.ng</span>
            </div>
          </div>
          <div className="flex items-center space-x-3 !text-sm">
            <a href="#" className="w-7 h-7 rounded-full bg-pink-600 flex items-center justify-center cursor-pointer">
              <FontAwesomeIcon icon={faCommentAlt} className="text-white text-xs" />
            </a>
            <a href="#" className="w-7 h-7 rounded-full bg-blue-500 flex items-center justify-center cursor-pointer">
              <FontAwesomeIcon icon={faFacebookF} className="text-white text-xs" />
            </a>
            <a href="#" className="w-7 h-7 rounded-full bg-blue-400 flex items-center justify-center cursor-pointer">
              <FontAwesomeIcon icon={faTwitter} className="text-white text-xs" />
            </a>
            <a href="#" className="w-7 h-7 rounded-full bg-pink-500 flex items-center justify-center cursor-pointer">
              <FontAwesomeIcon icon={faInstagram} className="text-white text-xs" />
            </a>
            <a href="#" className="w-7 h-7 rounded-full bg-red-500 flex items-center justify-center cursor-pointer">
              <FontAwesomeIcon icon={faYoutube} className="text-white text-xs" />
            </a>
            {/* <a href="#" className="ml-4 text-sm hover:underline cursor-pointer">LOGIN / REGISTER</a> */}
          </div>
        </div>
        {/* Navigation */}
        <div className="flex justify-between  h-15">
          <div className="px-8 bg-white flex items-center">
            <h1 className="text-2xl font-bold">
              <span className="text-gray-500">my</span>
              <span className="text-gray-700">HOME</span>
            </h1>
          </div>
          <nav className="flex-1 flex">
            <a href="#" className=" py-1 rounded-sm px-6 bg-white text-gray-600 flex items-center hover:bg-blue-800 transition-colors duration-200 cursor-pointer">Home</a>
            <a href="#" className="py-1  rounded-sm px-6 bg-white text-gray-600 flex items-center hover:bg-gray-100 transition-colors duration-200 cursor-pointer">About us</a>
            <a href="#" className="py-1  rounded-sm px-6 bg-white text-gray-600 flex items-center hover:bg-gray-100 transition-colors duration-200 cursor-pointer">Listings</a>
            <a href="#" className="py-1  rounded-sm px-6 bg-white text-gray-600 flex items-center hover:bg-gray-100 transition-colors duration-200 cursor-pointer">News</a>
            <a href="#" className="py-1  rounded-sm px-6 bg-white text-gray-600 flex items-center hover:bg-gray-100 transition-colors duration-200 cursor-pointer">Contact</a>
          </nav>
          <div className=" flex not-last-of-type:">
            <a href="#" className="py-5 px-8 m-2 rounded-sm bg-blue-700 text-black flex items-center hover:bg-pink-700 transition-colors duration-200 whitespace-nowrap cursor-pointer !rounded-button">
              LOGIN
            </a>
            <a href="#" className="py-5 px-8 m-2 rounded-sm bg-pink-600 text-black flex items-center hover:bg-pink-700 transition-colors duration-200 whitespace-nowrap cursor-pointer !rounded-button">
               REGISTER
            </a>
          </div>

        </div>
        {children}
        <footer className="bg-blue-700 text-white py-12">
          <div className="container mx-auto px-6">
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              <div>
                <h3 className="text-xl font-bold mb-4">About myHOME</h3>
                <p className="text-white mb-4">
                  myHOME is Nigeria's premier real estate platform, connecting buyers, sellers, and renters with the perfect properties across the country.
                </p>
                <div className="flex space-x-4">
                  <a href="#" className="text-white hover:text-white">
                    <FontAwesomeIcon icon={faFacebookF} className="text-xs" />
                  </a>
                  <a href="#" className="text-white hover:text-white">
                    <FontAwesomeIcon icon={faTwitter} className="text-xs" />
                  </a>
                  <a href="#" className="text-whit hover:text-white">
                    <FontAwesomeIcon icon={faInstagram} className="text-xs" />
                  </a>
                  <a href="#" className="text-white hover:text-white">
                    <FontAwesomeIcon icon={faLinkedinIn} className="text-xs" />
                  </a>
                </div>
              </div>
              <div>
                <h3 className="text-xl font-bold mb-4">Quick Links</h3>
                <ul className="space-y-2">
                  <li><a href="#" className="text-white hover:text-white">Home</a></li>
                  <li><a href="#" className="text-white hover:text-white">Properties</a></li>
                  <li><a href="#" className="text-white hover:text-white">Agents</a></li>
                  <li><a href="#" className="text-white hover:text-white">Blog</a></li>
                  <li><a href="#" className="text-white hover:text-white">Contact Us</a></li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-bold mb-4">Cities</h3>
                <ul className="space-y-2">
                  <li><a href="#" className="text-white hover:text-white">Lagos</a></li>
                  <li><a href="#" className="text-white hover:text-white">Abuja</a></li>
                  <li><a href="#" className="text-white hover:text-white">Port Harcourt</a></li>
                  <li><a href="#" className="text-white hover:text-white">Ibadan</a></li>
                  <li><a href="#" className="text-white hover:text-white">Kano</a></li>
                </ul>
              </div>
              <div>
                <h3 className="text-xl font-bold mb-4">Contact Us</h3>
                <ul className="space-y-2">
                  <li className="flex items-start">
                    <FontAwesomeIcon icon={faMapMarkerAlt} className="mt-1 mr-3 text-blue-500 text-xs" />
                    <span className="text-white">Victoria Island, Lagos, Nigeria</span>
                  </li>
                  <li className="flex items-start">
                    <FontAwesomeIcon icon={faPhoneAlt} className="mt-1 mr-3 text-blue-500 text-xs" />
                    <span className="text-white">+234 803 123 4567</span>
                  </li>
                  <li className="flex items-start">
                    <FontAwesomeIcon icon={faEnvelope} className="mt-1 mr-3 text-blue-500 text-xs" />
                    <span className="text-white">info@myhome.ng</span>
                  </li>
                </ul>
              </div>
            </div>
            <div className="border-t border-gray-700 mt-8 pt-8 text-center text-white">
              <p>&copy; 2023 myHOME. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
